import java.awt.Color;
import java.sql.*;
import javax.swing.*;

public class SignUp extends javax.swing.JFrame {
    
    private String role;
    
    public SignUp(String role) {
        initComponents();
        this.role = role;
        userRole.setText(role);
        
        getContentPane().setBackground(java.awt.Color.WHITE);
        modeBtn.setIcon(new ImageIcon(getClass().getResource("/Pictures/Sun.jpg")));
        modeBtn.setForeground(java.awt.Color.BLACK);
        isDarkMode = false;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userLogin = new javax.swing.JButton();
        signUp = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        passWord = new javax.swing.JPasswordField();
        showPass = new javax.swing.JCheckBox();
        userName = new javax.swing.JTextField();
        userEmail = new javax.swing.JTextField();
        userRole = new javax.swing.JLabel();
        modeBtn = new javax.swing.JToggleButton();
        sLogo1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        userLogin.setBackground(new java.awt.Color(102, 204, 255));
        userLogin.setForeground(new java.awt.Color(255, 255, 255));
        userLogin.setText("Login");
        userLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userLoginActionPerformed(evt);
            }
        });

        signUp.setBackground(new java.awt.Color(102, 204, 255));
        signUp.setForeground(new java.awt.Color(255, 255, 255));
        signUp.setText("Sign Up");
        signUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signUpActionPerformed(evt);
            }
        });

        jLabel2.setText("I already have an account.");

        passWord.setForeground(new java.awt.Color(153, 153, 153));
        passWord.setText("Password");
        passWord.setEchoChar('\u0000');
        passWord.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passWordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passWordFocusLost(evt);
            }
        });

        showPass.setText("Show Password");
        showPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPassActionPerformed(evt);
            }
        });

        userName.setForeground(new java.awt.Color(153, 153, 153));
        userName.setText("Username");
        userName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                userNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                userNameFocusLost(evt);
            }
        });
        userName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameActionPerformed(evt);
            }
        });

        userEmail.setForeground(new java.awt.Color(153, 153, 153));
        userEmail.setText("Email");
        userEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                userEmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                userEmailFocusLost(evt);
            }
        });
        userEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userEmailActionPerformed(evt);
            }
        });

        userRole.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        userRole.setText("User");

        modeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modeBtnActionPerformed(evt);
            }
        });

        sLogo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/MRJTL.png"))); // NOI18N
        sLogo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sLogo1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(showPass)
                    .addComponent(passWord, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userName, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(userLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(signUp, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(userRole, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(169, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(sLogo1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(modeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(modeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sLogo1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(userRole, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(userName, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(userEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(passWord, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(showPass)
                .addGap(41, 41, 41)
                .addComponent(signUp, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void signUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signUpActionPerformed
        String url = "jdbc:mysql://localhost:3306/mrjtl_db";
        String user = "root";
        String password = "";
        
        String name = userName.getText();
        String email = userEmail.getText();
        String passwordInput = passWord.getText();
        String role = userRole.getText();
        
        String sql = "INSERT INTO sign_up (username, email, password, status, role) VALUES (?, ?, ?, 'pending', ?)";
        
        if (name.isEmpty() || name.equals("Username")){
            JOptionPane.showMessageDialog(new JFrame(), "Username is required", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (email.isEmpty() || email.equals("Email")){
            JOptionPane.showMessageDialog(new JFrame(), "Email is required", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (passwordInput.isEmpty() || passwordInput.equals("Password")){
            JOptionPane.showMessageDialog(new JFrame(), "Password is required", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        try(Connection conn = DriverManager.getConnection(url, user, password);
            PreparedStatement stmt = conn.prepareStatement(sql)){
            
            stmt.setString(1, name);
            stmt.setString(2, email);
            stmt.setString(3, passwordInput);
            stmt.setString(4, role);
            
            int rowsInserted = stmt.executeUpdate();
            
            if (rowsInserted > 0){
                JOptionPane.showMessageDialog(this, "Sign up successful!");
            
                if (role.equalsIgnoreCase("Student")){
                    SRegistration userEnroll = new SRegistration();
                    userEnroll.setVisible(true);
                    this.dispose();
                } else if (role.equalsIgnoreCase("Faculty")){
                    Faculty facultyRegistration = new Faculty();
                    facultyRegistration.setVisible(true);
                    this.dispose();
                } else if(role.equalsIgnoreCase("Registrar")) {
                    JOptionPane.showMessageDialog(this, 
                    "Welcome, Registrar. Please contact the admin for further setup.", 
                    "Registrar Access", 
                    JOptionPane.INFORMATION_MESSAGE);
                }
            }
        } catch (SQLException ex){
            JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
            ex.printStackTrace();
        }
    }//GEN-LAST:event_signUpActionPerformed
    
    private void passWordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passWordFocusGained
        if (passWord.getText().equals("Password")){
            passWord.setText(null);
            passWord.setEchoChar('*');
            passWord.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_passWordFocusGained

    private void passWordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passWordFocusLost
        if (passWord.getText().equals("")){
            passWord.setText("Password");
            passWord.setEchoChar((char) 0);
            passWord.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_passWordFocusLost

    private void showPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPassActionPerformed
        if (passWord.getEchoChar() == '*'){
            passWord.setEchoChar((char) 0);
        } else {
            passWord.setEchoChar('*');
        }
    }//GEN-LAST:event_showPassActionPerformed

    private void userLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userLoginActionPerformed
        Logo login = new Logo(userRole.getText());
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_userLoginActionPerformed

    private void userNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userNameFocusGained
        if (userName.getText().equals("Username")){
            userName.setText("");
            userName.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_userNameFocusGained

    private void userNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userNameFocusLost
        if (userName.getText().equals("")){
            userName.setText("Username");
            userName.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_userNameFocusLost

    private void userNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userNameActionPerformed

    private void userEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userEmailActionPerformed

    private void userEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userEmailFocusGained
        if (userEmail.getText().equals("Email")){
            userEmail.setText("");
            userEmail.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_userEmailFocusGained

    private void userEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userEmailFocusLost
        if (userEmail.getText().equals("")){
            userEmail.setText("Email");
            userEmail.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_userEmailFocusLost
    private boolean isDarkMode = false;
    
    private void modeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modeBtnActionPerformed
        if (!isDarkMode) {
            getContentPane().setBackground(java.awt.Color.DARK_GRAY);
            modeBtn.setIcon(new ImageIcon(getClass().getResource("/Pictures/Moon.jpg")));
            modeBtn.setForeground(java.awt.Color.WHITE);
            
            userName.setBackground(java.awt.Color.DARK_GRAY);
            userName.setForeground(java.awt.Color.WHITE);
            userEmail.setBackground(java.awt.Color.DARK_GRAY);
            userEmail.setForeground(java.awt.Color.WHITE);
            passWord.setBackground(java.awt.Color.DARK_GRAY);
            passWord.setForeground(java.awt.Color.WHITE);
            showPass.setForeground(java.awt.Color.WHITE);
            jLabel2.setForeground(java.awt.Color.WHITE);
            userRole.setForeground(java.awt.Color.WHITE);

            isDarkMode = true;
        } else {
            getContentPane().setBackground(java.awt.Color.WHITE);
            modeBtn.setIcon(new ImageIcon(getClass().getResource("/Pictures/Sun.jpg")));
            modeBtn.setForeground(java.awt.Color.BLACK);
            
            userName.setBackground(java.awt.Color.WHITE);
            userName    .setForeground(new java.awt.Color(153, 153, 153));
            userEmail.setBackground(java.awt.Color.WHITE);
            userEmail.setForeground(new java.awt.Color(153, 153, 153));
            passWord.setBackground(java.awt.Color.WHITE);
            passWord.setForeground(new java.awt.Color(153, 153, 153));
            showPass.setForeground(java.awt.Color.BLACK);
            jLabel2.setForeground(java.awt.Color.BLACK);
            userRole.setForeground(java.awt.Color.BLACK);

            isDarkMode = false;
        }

        repaint();
    }//GEN-LAST:event_modeBtnActionPerformed

    private void sLogo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sLogo1ActionPerformed

    }//GEN-LAST:event_sLogo1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JToggleButton modeBtn;
    private javax.swing.JPasswordField passWord;
    private javax.swing.JButton sLogo1;
    private javax.swing.JCheckBox showPass;
    private javax.swing.JButton signUp;
    private javax.swing.JTextField userEmail;
    private javax.swing.JButton userLogin;
    private javax.swing.JTextField userName;
    private javax.swing.JLabel userRole;
    // End of variables declaration//GEN-END:variables
}
